language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

sudo: false

install:
    - travis_retry pip install --upgrade pip
    - travis_retry pip install wheel==0.26.0
    - travis_retry pip install invoke==0.13.0
    - travis_retry invoke install --develop

env:
  - WATERBUTLER_CONFIG=./travis-config.json

script:
  - invoke test

after_success:
  coveralls
