version: '3.7'

volumes:
  rabbitmq_vol:
    external: false
  av_requirements_vol:
    external: false

services:

  ###################
  # Shared Services #
  ###################

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_vol:/var/lib/rabbitmq
    stdin_open: true

  av_requirements:
    image: av:latest
    command: |-
      /bin/bash -c "
        invoke install --develop &&
        (python -m compileall /usr/local/lib/python3.6 || true) &&
        rm -Rf /python3.6/* &&
        cp -Rf -p /usr/local/lib/python3.6 /
      "
    restart: 'no'
    volumes:
      - av_requirements_vol:/python3.6

  av:
    image: av:latest
    command: invoke server
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file:
      - .docker-compose.av.env
    volumes:
      - av_requirements_vol:/usr/local/lib/python3.6
      - ./:/code:cached
    stdin_open: true

  av_worker:
    image: av:latest
    command: invoke celery
    restart: unless-stopped
    depends_on:
      - av
      - rabbitmq
    environment:
      C_FORCE_ROOT: 1
    env_file:
      - .docker-compose.av.env
    volumes:
      - av_requirements_vol:/usr/local/lib/python3.6
    stdin_open: true
