version: '3.7'

volumes:
  av_requirements_vol:
    external: false

services:

  ###################
  # Shared Services #
  ###################
  av_requirements:
    image: av:latest
    command: |-
      /bin/bash -c "
        invoke install --develop &&
        (python -m compileall /usr/local/lib/python3.6 || true) &&
        rm -Rf /python3.6/* &&
        cp -Rf -p /usr/local/lib/python3.6 /
      "
    restart: 'no'
    volumes:
      - av_requirements_vol:/python3.6

  av:
    image: av:latest
    command: invoke server
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file:
      - .docker-compose.av.env
    volumes:
      - av_requirements_vol:/usr/local/lib/python3.6
      - ./:/code:cached
    stdin_open: true
