name: py36
dependencies:
- pip=8.1.1=py36_0
- python=3.6.4=0
- setuptools=20.3=py35_0
- wheel=0.29.0=py35_0
- pip:
  - agent==0.1.2
  - aiohttp==0.18.2
  - git+https://github.com/felliott/boto.git@feature/gen-url-query-params-6#egg=boto
  - celery==3.1.17
  - furl==0.4.2
  - python-dateutil==2.5.3
  - stevedore==1.28.0
  - tornado==4.3
  - xmltodict==0.9.0
  - certifi==2015.4.28
