import hashlib

from aquavalet import settings


FILE_PATH_PENDING = '/tmp/pending'
FILE_PATH_COMPLETE = '/tmp/complete'

RUN_TASKS = False

HMAC_ALGORITHM = getattr(hashlib, 'sha256')

HMAC_SECRET = None

if not settings.DEBUG:
    assert HMAC_SECRET, 'HMAC_SECRET must be specified when not in debug mode'
HMAC_SECRET = (HMAC_SECRET or 'changeme').encode('utf-8')

# Retry options
UPLOAD_RETRY_ATTEMPTS = 1
UPLOAD_RETRY_INIT_DELAY = 30
UPLOAD_RETRY_MAX_DELAY = 60 * 60
UPLOAD_RETRY_BACKOFF = 2
UPLOAD_RETRY_WARN_IDX = 5

HOOK_RETRY_ATTEMPTS = 1
HOOK_RETRY_INIT_DELAY = 30
HOOK_RETRY_MAX_DELAY = 60 * 60
HOOK_RETRY_BACKOFF = 2
HOOK_RETRY_WARN_IDX = None

PARITY_RETRY_ATTEMPTS = 1
PARITY_RETRY_INIT_DELAY = 30
PARITY_RETRY_MAX_DELAY = 60 * 60
PARITY_RETRY_BACKOFF = 2
PARITY_RETRY_WARN_IDX = None

# Parity options
PARITY_CONTAINER_NAME = None
PARITY_REDUNDANCY = 5
PARITY_PROVIDER_NAME = 'cloudfiles'
PARITY_PROVIDER_CREDENTIALS = {}
PARITY_PROVIDER_SETTINGS = {}
